using Autodesk.AutoCAD.DatabaseServices;
using Autodesk.Civil.DatabaseServices;
using Grasshopper.Kernel;
using Rhino.Inside.AutoCAD.Civil.Interop;
using Rhino.Inside.AutoCAD.GrasshopperLibrary;
using Rhino.Inside.AutoCAD.Interop;

namespace Rhino.Inside.AutoCAD.Civil.GrasshopperLibrary;

/// <summary>
/// A Grasshopper component that extracts information from a Civil 3D Corridor.
/// </summary>
[ComponentVersion(introduced: "1.1.19")]
public class CivilCorridorComponent : RhinoInsideAutocad_ComponentBase
{
    /// <inheritdoc />
    public override Guid ComponentGuid => new("C9D0E1F2-A3B4-5678-9012-345678901ABC");

    /// <inheritdoc />
    protected override System.Drawing.Bitmap Icon => Properties.Resources.CivilCorridorComponent;

    /// <summary>
    /// Initializes a new instance of the <see cref="CivilCorridorComponent"/> class.
    /// </summary>
    public CivilCorridorComponent()
        : base("Civil3d Corridor", "CVL-Corr",
            "Extracts information from a Civil 3D Corridor",
            "Civil3d", "Corridors")
    {
    }

    /// <inheritdoc />
    protected override void RegisterInputParams(GH_InputParamManager pManager)
    {
        pManager.AddParameter(new Param_CivilCorridor(), "Corridor",
            "Corr", "A Civil3d Corridor", GH_ParamAccess.item);
    }

    /// <inheritdoc />
    protected override void RegisterOutputParams(GH_OutputParamManager pManager)
    {
        pManager.AddParameter(new Param_AutocadObjectId(GH_ParamAccess.item), "Id", "Id",
            "The Id of the Corridor.", GH_ParamAccess.item);

        pManager.AddParameter(new Param_CivilCorridorProperties(GH_ParamAccess.item), "Properties", "Props",
            "Corridor properties (use Corridor Properties component to extract values).", GH_ParamAccess.item);

        pManager.AddParameter(new Param_CivilCorridorBaseline(GH_ParamAccess.list), "Baselines", "BLs",
            "The baselines of the Corridor.", GH_ParamAccess.list);

        pManager.AddParameter(new Param_CivilCorridorBaselineRegion(GH_ParamAccess.list), "Regions", "Rgns",
            "All Baseline Regions from all Baselines.", GH_ParamAccess.list);

        pManager.AddParameter(new Param_CivilCorridorFeatureLine(GH_ParamAccess.list), "Feature Lines", "FLs",
            "All Feature Lines from all Baselines.", GH_ParamAccess.list);

        pManager.AddParameter(new Param_CivilCorridorSurface(GH_ParamAccess.list), "Surfaces", "Srfs",
            "The surfaces generated by the Corridor.", GH_ParamAccess.list);

        pManager.AddMeshParameter("Mesh", "M",
            "The combined corridor surfaces as a Rhino mesh.", GH_ParamAccess.item);
    }

    /// <inheritdoc />
    protected override void SolveInstance(IGH_DataAccess DA)
    {
        GH_CivilCorridor? corridorGoo = null;

        if (!DA.GetData(0, ref corridorGoo) || corridorGoo is null) return;

        var corridorId = corridorGoo.Reference.ObjectId;

        var document = this.GetDocumentForObjectId(corridorId);
        if (document is null)
        {
            this.AddRuntimeMessage(GH_RuntimeMessageLevel.Error, "No document available");
            return;
        }

        var transactionManager = document.CreateTransactionManager();

        var result = transactionManager.PerformTask(() =>
        {
            var corridor = transactionManager.Unwrap()
                .GetObject(corridorId.Unwrap(), OpenMode.ForRead) as Corridor;

            if (corridor == null)
            {
                return CorridorGooResult.Failed;
            }

            var wrapper = new CivilCorridorWrapper(corridor);

            var properties = wrapper.Properties;

            var propertiesGoo = new GH_CivilCorridorProperties(properties);

            var baselines = wrapper.GetBaselines(transactionManager);

            var baselinesGoo = new List<GH_CivilCorridorBaseline>();
            var allRegions = new List<GH_CivilCorridorBaselineRegion>();
            var allFeatureLines = new List<GH_CivilCorridorFeatureLine>();

            foreach (var baseline in baselines)
            {
                baselinesGoo.Add(new GH_CivilCorridorBaseline(baseline));

                // Get regions from this baseline
                var regions = baseline.GetRegions(transactionManager);
                allRegions.AddRange(regions.Select(r => new GH_CivilCorridorBaselineRegion(r)));

                // Get feature lines from this baseline
                var featureLines = baseline.GetFeatureLines(transactionManager);
                allFeatureLines.AddRange(featureLines.Select(fl => new GH_CivilCorridorFeatureLine(fl)));
            }

            var surfaces = wrapper.GetCorridorSurfaces(transactionManager);

            var surfacesGoo = surfaces.Select(s => new GH_CivilCorridorSurface(s))
                .ToList();

            var mesh = corridor.ToRhinoMesh(transactionManager);

            return new CorridorGooResult(propertiesGoo, baselinesGoo, allRegions, allFeatureLines, surfacesGoo, mesh);
        });

        if (result.IsSuccess == false)
        {
            this.AddRuntimeMessage(GH_RuntimeMessageLevel.Error, "Failed to read Corridor");
            return;
        }

        DA.SetData(0, new GH_AutocadObjectId(corridorId));
        DA.SetData(1, result.PropertiesGoo);
        DA.SetDataList(2, result.BaselinesGoo);
        DA.SetDataList(3, result.RegionsGoo);
        DA.SetDataList(4, result.FeatureLinesGoo);
        DA.SetDataList(5, result.SurfacesGoo);
        DA.SetData(6, result.Mesh);
    }
}
