using Autodesk.AutoCAD.DatabaseServices;
using Autodesk.Civil.DatabaseServices;
using Grasshopper.Kernel;
using Rhino.Inside.AutoCAD.Applications;
using Rhino.Inside.AutoCAD.Civil.Interop;
using Rhino.Inside.AutoCAD.GrasshopperLibrary;
using Rhino.Inside.AutoCAD.Interop;

namespace Rhino.Inside.AutoCAD.Civil.GrasshopperLibrary;

/// <summary>
/// A Grasshopper component that extracts information from a Civil 3D Corridor.
/// </summary>
[ComponentVersion(introduced: "1.2.19")]
public class CivilCorridorComponent : RhinoInsideAutocad_ComponentBase
{
    /// <inheritdoc />
    public override Guid ComponentGuid => new("C9D0E1F2-A3B4-5678-9012-345678901ABC");

    /// <inheritdoc />
    protected override System.Drawing.Bitmap Icon => Properties.Resources.CivilDefault;

    /// <summary>
    /// Initializes a new instance of the <see cref="CivilCorridorComponent"/> class.
    /// </summary>
    public CivilCorridorComponent()
        : base("Civil3d Corridor", "CVL-Corr",
            "Extracts information from a Civil 3D Corridor",
            "Civil3d", "Corridors")
    {
    }

    /// <inheritdoc />
    protected override void RegisterInputParams(GH_InputParamManager pManager)
    {
        pManager.AddParameter(new Param_CivilCorridor(), "Corridor",
            "Corr", "A Civil3d Corridor", GH_ParamAccess.item);
    }

    /// <inheritdoc />
    protected override void RegisterOutputParams(GH_OutputParamManager pManager)
    {
        pManager.AddParameter(new Param_AutocadObjectId(GH_ParamAccess.item), "Id", "Id",
            "The Id of the Corridor.", GH_ParamAccess.item);

        pManager.AddParameter(new Param_AutocadObjectId(GH_ParamAccess.item), "StyleId", "StyleId",
            "The Id of the Style of the Corridor.", GH_ParamAccess.item);

        pManager.AddParameter(new Param_CivilCorridorProperties(GH_ParamAccess.item), "Properties", "Props",
            "Corridor properties (use Corridor Properties component to extract values).", GH_ParamAccess.item);

        pManager.AddParameter(new Param_CivilCorridorBaseline(GH_ParamAccess.list), "Baselines", "BL",
            "The baselines of the Corridor.", GH_ParamAccess.list);

        pManager.AddParameter(new Param_CivilCorridorSurface(GH_ParamAccess.list), "Surfaces", "S",
            "The surfaces generated by the Corridor.", GH_ParamAccess.list);

        pManager.AddMeshParameter("Mesh", "M",
            "The combined corridor surfaces as a Rhino mesh.", GH_ParamAccess.item);
    }

    /// <inheritdoc />
    protected override void SolveInstance(IGH_DataAccess DA)
    {
        GH_CivilCorridor? corridorGoo = null;

        if (!DA.GetData(0, ref corridorGoo) || corridorGoo is null) return;

        var corridorId = corridorGoo.Reference.ObjectId;

        var document = RhinoInsideAutoCadExtension.Application.RhinoInsideManager
            .AutoCadInstance.ActiveDocument;

        var transactionManager = document.CreateTransactionManager();

        var corridor = transactionManager.PerformTask(() =>
            transactionManager.Unwrap().GetObject(corridorId.Unwrap(), OpenMode.ForRead) as
            Corridor);

        if (corridor == null)
        {
            this.AddRuntimeMessage(GH_RuntimeMessageLevel.Error, "Failed to read Corridor");
            return;
        }

        DA.SetData(0, new GH_AutocadObjectId(corridorId));

        DA.SetData(1, new GH_AutocadObjectId(new AutocadObjectIdWrapper(corridor.StyleId)));

        DA.SetData(2, new GH_CivilCorridorProperties(CivilCorridorProperties.CreateFromCorridor(corridor)));

        var corridorData = transactionManager.PerformTask(() => new
        {
            Baselines = corridor.GetBaselines(transactionManager),
            Surfaces = corridor.GetCorridorSurfaces(transactionManager),
            Mesh = corridor.ToRhinoMesh(transactionManager)
        });

        DA.SetDataList(3, corridorData.Baselines.Select(b => new GH_CivilCorridorBaseline(b)).ToList());
        DA.SetDataList(4, corridorData.Surfaces.Select(s => new GH_CivilCorridorSurface(s)).ToList());
        DA.SetData(5, corridorData.Mesh);
    }
}
