using Grasshopper.Kernel;
using Rhino.Inside.AutoCAD.GrasshopperLibrary;

namespace Rhino.Inside.AutoCAD.Civil.GrasshopperLibrary;

/// <summary>
/// A Grasshopper component that extracts individual values from Civil 3D Corridor Properties.
/// </summary>
[ComponentVersion(introduced: "1.2.19")]
public class CivilCorridorPropertiesComponent : RhinoInsideAutocad_ComponentBase
{
    /// <inheritdoc />
    public override Guid ComponentGuid => new("D0E1F2A3-B4C5-6789-0123-456789012BCD");

    /// <inheritdoc />
    protected override System.Drawing.Bitmap Icon => Properties.Resources.CivilDefault;

    /// <summary>
    /// Initializes a new instance of the <see cref="CivilCorridorPropertiesComponent"/> class.
    /// </summary>
    public CivilCorridorPropertiesComponent()
        : base("Civil3d Corridor Properties", "CVL-CorrProps",
            "Extracts individual values from Civil 3D Corridor Properties",
            "Civil3d", "Corridors")
    {
    }

    /// <inheritdoc />
    protected override void RegisterInputParams(GH_InputParamManager pManager)
    {
        pManager.AddParameter(new Param_CivilCorridorProperties(GH_ParamAccess.item), "Properties",
            "Props", "Corridor properties from a Civil3d Corridor", GH_ParamAccess.item);
    }

    /// <inheritdoc />
    protected override void RegisterOutputParams(GH_OutputParamManager pManager)
    {
        pManager.AddTextParameter("Name", "N",
            "The name of the corridor.", GH_ParamAccess.item);

        pManager.AddTextParameter("Description", "Desc",
            "The description of the corridor.", GH_ParamAccess.item);

        pManager.AddNumberParameter("Start Station", "StaSt",
            "The starting station of the corridor.", GH_ParamAccess.item);

        pManager.AddNumberParameter("End Station", "StaEnd",
            "The ending station of the corridor.", GH_ParamAccess.item);

        pManager.AddNumberParameter("Length", "Len",
            "The total length of the corridor.", GH_ParamAccess.item);

        pManager.AddIntegerParameter("Baseline Count", "BLCount",
            "The number of baselines in the corridor.", GH_ParamAccess.item);

        pManager.AddIntegerParameter("Surface Count", "SrfCount",
            "The number of surfaces generated by the corridor.", GH_ParamAccess.item);
    }

    /// <inheritdoc />
    protected override void SolveInstance(IGH_DataAccess DA)
    {
        GH_CivilCorridorProperties? propsGoo = null;

        if (!DA.GetData(0, ref propsGoo) || propsGoo?.Value is null) return;

        var props = propsGoo.Value;

        DA.SetData(0, props.Name);
        DA.SetData(1, props.Description);
        DA.SetData(2, props.StartStation);
        DA.SetData(3, props.EndStation);
        DA.SetData(4, props.Length);
        DA.SetData(5, props.BaselineCount);
        DA.SetData(6, props.SurfaceCount);
    }
}
