using Autodesk.AutoCAD.DatabaseServices;
using Autodesk.Civil.DatabaseServices;
using Grasshopper.Kernel;
using Rhino.Inside.AutoCAD.Applications;
using Rhino.Inside.AutoCAD.GrasshopperLibrary;
using Rhino.Inside.AutoCAD.Interop;

namespace Rhino.Inside.AutoCAD.Civil.GrasshopperLibrary;

/// <summary>
/// A Grasshopper component that gets all Surfaces from a Civil 3D Corridor.
/// </summary>
[ComponentVersion(introduced: "1.2.19")]
public class GetSurfacesFromCorridorComponent : RhinoInsideAutocad_ComponentBase
{
    /// <inheritdoc />
    public override Guid ComponentGuid => new("E7F8A9B0-C1D2-3456-7890-123456789234");

    /// <inheritdoc />
    protected override System.Drawing.Bitmap Icon => Properties.Resources.CivilDefault;

    /// <summary>
    /// Initializes a new instance of the <see cref="GetSurfacesFromCorridorComponent"/> class.
    /// </summary>
    public GetSurfacesFromCorridorComponent()
        : base("Get Corridor Surfaces", "CVL-GetCorrSrfs",
            "Gets all Surfaces from a Civil 3D Corridor",
            "Civil3d", "Corridors")
    {
    }

    /// <inheritdoc />
    protected override void RegisterInputParams(GH_InputParamManager pManager)
    {
        pManager.AddParameter(new Param_CivilCorridor(), "Corridor",
            "Corr", "A Civil3d Corridor to get surfaces from", GH_ParamAccess.item);
    }

    /// <inheritdoc />
    protected override void RegisterOutputParams(GH_OutputParamManager pManager)
    {
        pManager.AddParameter(new Param_CivilCorridorSurface(GH_ParamAccess.list), "Surfaces", "Srfs",
            "The Surfaces generated by this Corridor.", GH_ParamAccess.list);

        pManager.AddMeshParameter("Meshes", "M",
            "The surfaces as Rhino meshes.", GH_ParamAccess.list);
    }

    /// <inheritdoc />
    protected override void SolveInstance(IGH_DataAccess DA)
    {
        GH_CivilCorridor? corridorGoo = null;

        if (!DA.GetData(0, ref corridorGoo) || corridorGoo is null) return;

        var corridorId = corridorGoo.Reference.ObjectId;

        var document = RhinoInsideAutoCadExtension.Application.RhinoInsideManager
            .AutoCadInstance.ActiveDocument;

        var transactionManager = document.CreateTransactionManager();

        var result = transactionManager.PerformTask(() =>
        {
            var corridor = transactionManager.Unwrap()
                .GetObject(corridorId.Unwrap(), OpenMode.ForRead) as Corridor;

            if (corridor == null)
                return (Surfaces: new List<GH_CivilCorridorSurface>(),
                        Meshes: new List<Rhino.Geometry.Mesh>());

            var surfaces = corridor.GetCorridorSurfaces(transactionManager);
            var surfaceGoos = surfaces.Select(s => new GH_CivilCorridorSurface(s)).ToList();
            var meshes = surfaces.Where(s => s.Mesh != null).Select(s => s.Mesh!).ToList();

            return (Surfaces: surfaceGoos, Meshes: meshes);
        });

        if (result.Surfaces.Count == 0)
        {
            this.AddRuntimeMessage(GH_RuntimeMessageLevel.Warning, "No surfaces found in this corridor");
            return;
        }

        DA.SetDataList(0, result.Surfaces);
        DA.SetDataList(1, result.Meshes);
    }
}
