using Autodesk.Civil.DatabaseServices;
using Rhino.Geometry;
using Rhino.Inside.AutoCAD.Core.Interfaces;
using Rhino.Inside.AutoCAD.Interop;

namespace Rhino.Inside.AutoCAD.Civil.Interop;

/// <summary>
/// Wraps a surface generated by a Civil 3D Corridor.
/// </summary>
/// <remarks>
/// This wrapper captures corridor surface data at construction time from a <see cref="CorridorSurface"/>.
/// </remarks>
public class CivilCorridorSurfaceWrapper : AutocadWrapperBase<CorridorSurface>, ICivilCorridorSurface
{
    /// <inheritdoc />
    public string Name { get; }

    /// <inheritdoc />
    public IObjectId SurfaceId { get; }

    /// <summary>
    /// Gets the Rhino mesh representation of this corridor surface.
    /// </summary>
    public Mesh? Mesh { get; }

    /// <summary>
    /// Initializes a new instance of <see cref="CivilCorridorSurfaceWrapper"/>
    /// from a Civil 3D CorridorSurface.
    /// </summary>
    /// <param name="surface">The corridor surface to extract data from.</param>
    /// <param name="mesh">Optional pre-computed Rhino mesh.</param>
    public CivilCorridorSurfaceWrapper(CorridorSurface surface, Mesh? mesh = null) : base(surface)
    {
        this.Name = surface.Name ?? string.Empty;
        this.SurfaceId = new AutocadObjectIdWrapper(surface.SurfaceId);
        this.Mesh = mesh;
    }

    /// <summary>
    /// Creates a duplicate of this corridor surface wrapper.
    /// </summary>
    /// <returns>A new instance with the same wrapped object and duplicated mesh.</returns>
    public CivilCorridorSurfaceWrapper Duplicate()
    {
        return new CivilCorridorSurfaceWrapper(_wrappedAutocadObject, this.Mesh?.DuplicateMesh());
    }

    /// <inheritdoc />
    public override string ToString()
    {
        return $"Corridor Surface: {this.Name})";
    }
}
