namespace Rhino.Inside.AutoCAD.Core.Interfaces;

/// <summary>
/// Represents a surface generated by a Civil 3D Corridor.
/// </summary>
/// <remarks>
/// Corridor surfaces are TIN surfaces generated from the corridor
/// feature lines and cross-section data.
/// </remarks>
public interface ICivilCorridorSurface
{
    /// <summary>
    /// Gets the name of the corridor surface.
    /// </summary>
    string Name { get; }

    /// <summary>
    /// Gets the ObjectId of the generated TIN surface.
    /// </summary>
    IObjectId SurfaceId { get; }
}
