<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>$(TargetFrameworkName)</TargetFramework>
		<Configurations>Release;Debug;ReleaseNET8;DebugNET8;ReleaseNET10;DebugNET10</Configurations>
		<ImplicitUsings>enable</ImplicitUsings>
		<OutputType>WinExe</OutputType>
		<Nullable>enable</Nullable>
		<LangVersion>preview</LangVersion>
		<Version>$(AssemblyVersion)</Version>
		<Company>$(BimorphCompany)</Company>
		<Product>$(BimorphProduct)</Product>
		<Copyright>$(BimorphCopyright)</Copyright>
		<UseWPF>true</UseWPF>
		<UseWindowsForms>true</UseWindowsForms>
		<GenerateDocumentationFile>True</GenerateDocumentationFile>
		<ProduceReferenceAssembly>True</ProduceReferenceAssembly>
		<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
	</PropertyGroup>

	<ItemGroup>
		<Reference Include="PresentationCore" />
		<PackageReference Include="System.Drawing.Common" />
		<PackageReference Include="Serilog" />
		<PackageReference Include="System.Text.Json" />
		<PackageReference Include="RhinoCommon">
			<ExcludeAssets>runtime</ExcludeAssets>
		</PackageReference>
		<PackageReference Include="Grasshopper">
			<ExcludeAssets>runtime</ExcludeAssets>
		</PackageReference>
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Rhino.Inside.AutoCAD.Core\Rhino.Inside.AutoCAD.Core.csproj" />
		<ProjectReference Include="..\Rhino.Inside.AutoCAD.Services\Rhino.Inside.AutoCAD.Services.csproj" />
		<ProjectReference Include="..\Rhino.Inside.AutoCAD.Interop\Rhino.Inside.AutoCAD.Interop.csproj" />
	</ItemGroup>

	<Target Name="PostBuild" AfterTargets="PostBuildEvent">
		<Exec Command="xcopy /y /i &quot;$(OutDir)*.exe&quot; &quot;$(AppRootDirAssemblies)&quot;&#xD;&#xA;xcopy /y /i &quot;$(OutDir)*.pdb&quot; &quot;$(AppRootDirAssemblies)&quot;&#xD;&#xA;&#xD;&#xA;xcopy /y /i &quot;$(OutDir)*.exe&quot; &quot;$(DeploymentPackage_Win64)&quot;" />
	</Target>

</Project>
